### PR TITLE
Get alos pasar

### PR DESCRIPTION
**Pull request by h-a-graham**
Hey @mikemahoney218 this adds a wrapper for getting the ALOS PASLSAR annual mosaic. Includes band mapping and masks. 

Only extra thing I was wondering is whether we should consider providing a helper function for converting digital numbers to backscatter or whether the note in the docs is sufficient? 

let me know what you think  and happy to review anything as needed! 

Cheers, 
Hugh

### CODE REVIEW

**Comment by mikemahoney218** [comment]
Looks awesome -- just missing documentation in `R/data.R`. I'd be happy to add this, or you can!

> should consider providing a helper function for converting digital numbers to backscatter or whether the note in the docs is sufficient

I _think_ the note is fine for right now. I've got a dream of turning the internals of `get_stac_data()` into a handful of composable functions -- so you could call `get_stac_data(query_function = query_stac_api(), download_function = download_stac_assets())` and so on, or alternatively have a pipeline where you run `query_stac_api() |> download_stac_assets()` if you prefer. Once I move towards that (which is firmly "after I send the final draft of my dissertation out"), then it might be nice to have `rescale_alos_palsar()` as one of those functions, but until then I think the note is good!

**Comment by mikemahoney218** [comment]
Sorry, think I just mucked your branch up -- I rebased it onto the current `main`, completely forgetting that would mess up the branch history if you wanted to push any other commits.

**Comment by h-a-graham** [comment]
Sounds good. Ah yes I forgot about the data docs! I don't mind doing this tomorrow.

I really like the sound of your suggestion and totally agree it is non-essential right now. Besides it also gets confusing when applying certain indices. I love the idea of being able to construct processing pipelines that's a cool idea!

**Comment by h-a-graham** [comment]
Sorry I missed the last comment as I  was on my phone. No worries, I'll take a look to see if it matters but if it's easier for you to now just fix the doc issue then please feel free!

**Comment by mikemahoney218** [comment]
I've now _super_ messed up the commit history, but this is merged as of https://github.com/Permian-Global-Research/rsi/commit/120a8b2083797d56e144440646bbff8f5ca38051

**Pull request closed without merging**
